#+title: Husky Hunt App

This is an app designed to be used by our team during Northeastern's Husky Hunt Competition

* Deploying
*After Frontend Changes*:
- Commit changes and merge them into the master branch
- Run the command "yarn run deploy"
- After a minute or two, the changes should automatically be seen at https://huskyhunties.github.io/hh-app/

*After Backend Changes*:


* Logistics
*API Team*:
- Michael
- Matt
- Dan
- Ben

*Web Team*:
- Max
- Ryan
- Olivia

*Team which decides the features*:
- Shurobhi
- Owen
- everyone else

** Creating Routes
At a high level, a REST API is organized into routes. Each route provides a
logically grouped subset of the API functionality. For example,
`www.api.com/map/...` might represent the `map` route, and provide all
functionality related to adding or retrieving map information.

In the code, the implementations for different routes are similarly partitioned.
In `controllers`, there is a file for each high level route, and these files are
imported in `controllers/main.ts` and then added as routes in the express app
instance.

** Funky Behavior Notes
- I couldn't get breakpoints working in VS Code.
 
  Breakpoints only function if, when evaluating code.js, VS Code "knows about"
  (?) the source map. The Source Map is a build artifact of the typescript
  compilation, so first I had to tell gulp to generate these map files. I then
  had to tell VS Code to look for source files (launch.json) then I had to tell
  Typescript that source files existed ("sourceFiles": true in tsconfig.json).
 
  The last setting is required to set breakpoints in typescript source, but
  without it, I can still set and use breakpoints in js build files. This is
  weird, since it doesn't seem that "sourceFiles": true has any concrete effect
  on the creation or linking of the source files.

* Configuration
** Initializing the Database
First, install sqlite3 if you haven't:
- Linux: install sqlite3 with your package manager!
- OSX: install 'homebrew' if you have not already. https://brew.sh/, then
  install sqlite3 with ~brew cask install sqlite3~
- Windows: https://www.sqlitetutorial.net/download-install-sqlite/

Creating the database:
#+begin_src bash
$ cd src
$ sqlite3 {database name}.db < initDB.sql
#+end_src

It is of note that we have a database file in this repository
(at ~src/database.db~), but it's possible that others may want to create new
databases or reset the current database.
